### ISSUE TITLE
Automatically activate (and deactivate) the WordPress Importer plugin

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/import-command#36]
When running `wp import` with the WordPress Importer plugin installed but not active, the following error message is shown:

    Error: WordPress Importer needs to be activated. Try 'wp plugin activate wordpress-importer'.

It would be more user-friendly if the `wp import` command automatically activated the plugin if it's installed, and then deactivated it after the import is complete.

If the plugin is not installed, or if it's installed and already activated, there should be no change in behaviour.

**Comment by schlessera** [comment]
Instead of actually activating it, we should filter the list of active plugins and add it. I don't think it needs an activation hook or similar, so that is the safest operation I guess, i.e. it makes sure the plugin does not stay activated in case of an error, for example.

**Comment by johnbillion** [comment]
Good idea

**Comment by abhijitrakas** [comment]
@johnbillion @schlessera 

In another case, if `WordPress-importer` plugin is not installed then it gives the following error.

```
WordPress Importer needs to be installed. Try 'wp plugin install WordPress-importer --activate'.
```
Could we handle this situation using any of the following two options?
* [ ] Install plugin directly without asking user as this plugin is required.
* [ ] Can prompt up and ask the user to install the plugin? If the user agrees then we can install plugin else we can halt the process.

**Comment by danielbachhuber** [comment]
I think this violates WP-CLI's [composability philosophy](https://make.wordpress.org/cli/handbook/philosophy/#composability-is-always-a-good-idea):

> A corollary of this is that commands should be orthogonal, which means that there should be no overlapping functionality between commands. (`wp plugin install --activate` is an exception).

**Comment by schlessera** [comment]
Yes, I don't think the plugin should be installed by the import command. Maybe there is a reason why it is not installed, we shouldn't interfere with that. It is pretty easy for the user to just copy the provided command and run it.
However, when it is already installed, but not active, I still think filtering the list of active plugins makes sense as a very common shortcut. It is available and would be ready for use, but would force you to "activate - run command - deactivate" if they don't intend for the importer to stay active when not in use.

**Comment by danielbachhuber** [comment]
> However, when it is already installed, but not active, I still think filtering the list of active plugins makes sense as a very common shortcut. It is available and would be ready for use, but would force you to "activate - run command - deactivate" if they don't intend for the importer to stay active when not in use.

Fair enough, this seems reasonable.

**Comment by abhijitrakas** [comment]
@schlessera @danielbachhuber 

I have tried to activate the plugin using filter `option_active_plugins` but, this filter not working during the `import` command. Instead, when I run `wp plugin list` I found the plugin is activated by using a filter.

The other way I tried is by requiring a plugin file something like `require_once ABSPATH . 'wp-content/plugins/wordpress-importer/wordpress-importer.php';` and this working but, not sure this is expected or not.

**Comment by schlessera** [comment]
@abhijitrakas Using the `option_active_plugins` filter within the `import` command is too late, as WordPress will have been completely loaded at that point.

You will need to hook additional code to filter the plugins into the **registration** of the command, not where the command is **invoked**.

In there, it is not yet too late to run the `option_active_plugins` hook.

So, the registration flow would be:

1. Check if `WordPress-importer` plugin is installed. If not, bail with `WP_CLI::error()`.
2. Check if `WordPress-importer` plugin is active. If not, filter `active_plugins`.
3. Register `import` command.

**Comment by schlessera** [comment]
No, sorry, scrap the last bit, that will always break WP_CLI...

Hmm, we want to run these checks only when the command is actually invoked, but at the point of invocation, it is too late to act on it.

That would mean we need to "pre-parse" the arguments in the command registration code. That sounds like we need a new helper function first... Let me think some more on that.
