### ISSUE TITLE
Out of memory: Killed process 3541210 (php)

### ISSUE THREAD

**Issue by 832Mishanya** [wp-cli/import-command#65]
--------------^ Click "Preview" for a nicer view!

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review [http://wp-cli.org/#support](http://wp-cli.org/#support).

The easiest way to get support is to join us in the [`#cli`](https://wordpress.slack.com/messages/C02RP4T41) channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
Hello, I tried to import a 600mb .wxr file, but after starting the import I get the message "Killed"
I found only this in the logs, tell me how you can solve this error. I understand that there is not enough memory
issue log:

oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-9443.scope,task=php,pid=3541210,uid=0  
                             
Out of memory: Killed process 3541210 (php) total-vm:3055668kB, anon-rss:2493496kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:5040kB oom_score_adj:0   
                                                 
oom_reaper: reaped process 3541210 (php), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by schlessera** [comment]
This is a problem with the WordPress importer plugin that is used behind the scenes and does require lots of memory to process an import. One solution you can try is to split the export into multiple smaller files while exporting.

A future version of WP-CLI will try to get away from the official importer plugin, as it doesn't get the required maintenance.
