### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_error_message() on int in \plugins\wordpress-importer\class-wp-import.php:414

### ISSUE THREAD

**Issue by DrLightman** [wp-cli/import-command#72]
## Bug Report

**Describe the current, buggy behavior**

Fatal error here:

```
D:\Sites\wordpress>wp import test.xml --authors=create --skip=image_resize
Starting the import process...
Failed to import category televisione
Fatal error: Uncaught Error: Call to a member function get_error_message() on int in D:\Sites\wordpress\wp-content\plugins\wordpress-importer\class-wp-import.php:414
Stack trace:
#0 D:\Sites\wordpress\wp-content\plugins\wordpress-importer\class-wp-import.php(85): WP_Import->process_categories()
#1 phar://C:/wp-cli/wp-cli.phar/vendor/wp-cli/import-command/src/Import_Command.php(179): WP_Import->import('test.xml')
#2 phar://C:/wp-cli/wp-cli.phar/vendor/wp-cli/import-command/src/Import_Command.php(81): Import_Command->import_wxr('test.xml', Array)
#3 [internal function]: Import_Command->__invoke(Array, Array)
#4 phar://C:/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#5 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#6 phar://C:/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#7 phar://C:/wp-cli/wp-cli.phar/vendor/wp-cli/w in D:\Sites\wordpress\wp-content\plugins\wordpress-importer\class-wp-import.php on line 414
```

There are two issues.

**First issue**, `$id->get_error_message()` on `$id` being an int not a `WP_Error`. (easy fix scrolling below)

**Second issue**, category information on xml obtained with an export filtered by category is scarce, it lacks the name, "Televisione" in my case:

```
<wp:category>
  <wp:term_id>6</wp:term_id>
  <wp:category_nicename>televisione</wp:category_nicename>
  <wp:category_parent/>
</wp:category>
```

**Describe how other contributors can replicate this bug**

- create an export file filtered by category, for instance with `wp export --post_type=post --category=mycat` rename it to test.xml to make it simple. I had to do it in a WP 5.3.6 .
- import the aforementioned export file into an empty WP installation, for instance with: `wp import test.xml --authors=create --skip=image_resize` . I had to do it in a WP 5.7.2 .
- sit and enjoy the fatal error

**Describe what you would expect as the correct outcome**

To import without fatal errors or at least to be able to read the actual error message.

Once I managed to fix an error in the WordPress Importer plugin code I was able to read the actual error message, and it says:

```
D:\Sites\wordpress>wp import test.xml --authors=create --skip=image_resize
Starting the import process...
Failed to import category televisione: You did not enter a category name.
```

To further fix that error I had to delete the scarce category information that is printed at the top of the xml so letting the Importer to use the on embedded in the post <item>.

Scarce information I manually removed from test.xml to avoid Fatal Error:

```
<wp:category>
  <wp:term_id>6</wp:term_id>
  <wp:category_nicename>televisione</wp:category_nicename>
  <wp:category_parent/>
</wp:category>
```

Correct information embedded in the post <item> that the importer will use:

```
<category domain="category" nicename="televisione"><![CDATA[Televisione]]></category>
```

**Let us know what environment you are running this on**

```
OS:     Windows NT 10.0 build 19043 (Windows 10) AMD64
Shell:  C:\WINDOWS\system32\cmd.exe
PHP binary:     C:\fbampp\php\php.exe
PHP version:    7.4.2
php.ini used:   C:\fbampp\php\php.ini
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       D:\Sites\wordpress
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0
```

**Provide a possible solution**

Pass `true` as second parameter here, not leave empty:

```php
$id = wp_insert_category( $data, true );
```
file: \wp-content\plugins\wordpress-importer\class-wp-import.php line 407 of WordPress Importer ver 0.7

Fix the `wp export --post_type=post --category=catname` command so it prints full correct category information at the top of the xml file (or remove it completely but I'm not sure of this)

**Comment by danielbachhuber** [comment]
Thanks for the report, @DrLightman !

It looks like this issue was fixed in v0.8.0 of the WordPress Importer: https://github.com/WordPress/wordpress-importer/pull/123
