### ISSUE TITLE
The `post_modified` field is filled with the wrong value as a result of the import operation

### ISSUE THREAD

**Issue by trytofinderror** [wp-cli/import-command#81]
After performing export-import operations between WordPress installations on the same server, I get the value of the `post_modified` field in the target database that does not match the value in the source and in the export file.
The value in the export file is correct.

`wp export --skip_comments --post__in=1234 --path=/path/to/wordpress --dir=/path/to/wxr --with_attachments --filename_format=1234.xml;`

`wp import --path=/path/to/another/wordpress --authors=create /path/to/wxr/1234.xml; `

In source database: `[{"post_modified":"2023-03-02 14:21:47"}]`
In wxr file: `<wp:post_modified>2023-03-02 14:21:47</wp:post_modified>`
In target database: `[{"post_modified":"2023-02-03 10:25:06"}]`

**Comment by danielbachhuber** [comment]
Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
