### ISSUE TITLE
import from stdin

### ISSUE THREAD

**Issue by drzraf** [wp-cli/import-command#9]
That would be great, one could import compressed/encrypted/whatevered XHR xml bytes stream using Unix pipes rather than uncompressing/creating copy.
An alternative would be the ability for `wp import` to open compressed files. But opening from stdin seems like a more versatile way to do it.

**Comment by danielbachhuber** [comment]
> That would be great, one could import compressed/encrypted/whatevered XHR xml bytes stream using Unix pipes rather than uncompressing/creating copy.

Could you explain in more detail why this would be helpful, or why reading from the filesystem isn't sufficient?

One concern is that WXR data is typically quite large, which is why they're split into multiple files. On larger datasets, you'd likely crash your PHP before the entirety of the stream was written into memory.

**Comment by drzraf** [comment]
`wp-cli` handles gz (using `gzopen` internally).
But I've a 50 MB xhr that I compressed-down to ... 800 KB using xz.
Sadly xz is not part of php yet and I'd have liked to pipe `xzcat|wp-cli import`

But anyway, issue can be closed because I looked at:
[wordpress-importer](https://plugins.trac.wordpress.org/browser/wordpress-importer/trunk/wordpress-importer.php) which depends upon [WXR_Parser_SimpleXML->parse()](https://plugins.trac.wordpress.org/browser/wordpress-importer/trunk/parsers.php#L55)
which does `$dom->loadXML( file_get_contents( $file ) );`
The alternative parser `xml_parse( $xml, file_get_contents( $file ), true ) )` . Not better.

According to [this](https://stackoverflow.com/a/911674), [XMLReader](http://se2.php.net/manual/en/book.xmlreader.php) would be a good option.

I finally found https://github.com/humanmade/WordPress-Importer which is exactly that: an importer based upon the [XMLReader->open](https://github.com/humanmade/WordPress-Importer/blob/master/class-wxr-importer.php#L123) PHP interface. But ... is it really [stream-compatible](https://bugs.php.net/bug.php?id=46146)...
